import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dashboard Layout',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex flex-1 justify-center flex-col">{children}</main>
  );
}
